### ISSUE TITLE
Generated Artifacts seem incomplete

### ISSUE THREAD

**Issue by ReneHabermann** [dailymotion/allure-go#26]
Hi, thank you for bringing allure to go! 

I cloned your repo and ran an example, namely _TestFailedExample_ from _example_test.go_. It runs fine so far and allure results are produced. What i would have expected is an html allure report and maybe some other files. However, i only get a json with this content:
`{"uuid":"2599fade-d27d-4ee5-b6d4-5a797861a257","name":"Failed Example","description":"This is a test to show allure implementation with a failing test","status":"failed","stage":"finished","start":1583146472741,"stop":1583146472741,"fullName":"/home/rene/go/src/allure-go/example/example_test.go:TestFailedExample","labels":[{"name":"package","value":"home.rene.go.src.allure-go.example.example_test"},{"name":"testClass","value":"home.rene.go.src.allure-go.example.example_test"},{"name":"testMethod","value":"TestFailedExample"},{"name":"host","value":"<removed>"},{"name":"language","value":"golang"}]}`

I guess this is not the desired output. The json seems to be also missing the assertion error, but maybe this is as intended ("Expected empty string, but got Hello world ")

I am using go1.13.1 linux/amd64 with Ubuntu 18.04.3 LTS

Please let me know if i can provide additional information.

**Comment by Ubermensch01** [comment]
@ReneHabermann thank you for using our library!
Unfortunately, `allure-go` is unable to intercept Go's builtin error handling approaches. `t.Errorf` in this test script fails a test and outputs the statement in the output log. In order to handle errors so that they were displayed in the report, please use `allure.Fail()`, `allure.FailNow()`, `allure.Break()` and `allure.BreakNow()`. These functions will save error messages to the test objects so that they could be displayed in the report.

In order to generate an allure report run `allure generate` that will create a folder called `allure-report` with all the report assets. If you want to serve report immediately, run `allure serve`, it will temporarily generate the report  and open it in your default browser.

Please let me know if this helped.

**Comment by ReneHabermann** [comment]
Thank you very much for your reply, that helped greatly and made everything clear. Maybe this could be improved in the doc. I hope i didn't miss it, bit i didn't see a mention of `allure.Fail() `and friends, and the code example is also not using it (https://github.com/dailymotion/allure-go/blob/master/example/example_test.go).

In the same wake, as coming with no prior experience in allure, i wasn't aware of the allure cli being needed here. But i would have found out about it, if it would have been clear, what the expected result of a test run with allure-go is. Maybe you can add an example what should be produced if the run was ok? Just as a suggestion.

Thank you again, i'll close the issue as there was'nt actually one.

**Comment by Ubermensch01** [comment]
@ReneHabermann These are good points. Documentation for error handling is already in the works and giving more context of the outputs of `allure-go` is a good idea, thank you for suggesting it.
