### ISSUE TITLE
Allure report doesn't contain failure information

### ISSUE THREAD

**Issue by aianushevich** [dailymotion/allure-go#41]
Hello. I have a problem with allure reports generating. My allure reports don't contain any technical information or stack traces about tests failures.

For example, I have a test with typical require.Equals statement from testify. This test always fails (for reproducing a problem):
```
package suites

import (
	"testing"

	"github.com/dailymotion/allure-go"
	"github.com/stretchr/testify/require"
)

func TestExample(t *testing.T) {
	allure.Test(t,
		allure.Description("Example test"),
		allure.Action(func() {
			allure.Step(
				allure.Description("First step"),
				allure.Action(func() {
					require.Equal(t, "one", "two") // always failed
				}))
		}))
}
```

This test fails with error:
```
Error:      	Not equal: 
        	            	expected: "one"
        	            	actual  : "two"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-one
        	            	+two
        	Test:       	TestExample
--- FAIL: TestExample (0.00s)
```

But allure report doesn't contains any errors:
```
...
"uuid": "5fe18803-ff95-4d56-b45a-0911ab2ab98e",
  "testCaseId": "b79ae15a1d2cc3c6065798bd441a8719a302efe777767dc8ed277ef12666fb3d",
  "historyId": "b79ae15a1d2cc3c6065798bd441a8719a302efe777767dc8ed277ef12666fb3d",
  "name": "Example",
  "description": "Example test",
  "status": "failed",
  "stage": "finished",
  "steps": [
    {
      "name": "First step",
      "status": "failed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1643704550868,
      "stop": 1643704550868
    }
  ]
...
```

I am expecting report with statusDetails field, like you do in Fail or FailNow functions.

Looks like your feature roadmap already contains this feature, but maybe I do smth wrong...

**Comment by MaximeBellou** [comment]
@aianushevich this is expected.
If I am correct, when @ubermensch01 implemented the creation of allure result files, there was no way for us to listen to test failure, and insert the error message in the test result file. It needs to be managed at the project (that uses allure-go) level.
This is why we implemented the Fail/FailNow/Break/BreakNow methods, to store the stack trace in the result object.
There are 2 ways to implement a solution to this constraint:
- Use testify assert instead or require, so the method returns a boolean that can be used on a condition:
```
package suites

import (
	"testing"

	"github.com/dailymotion/allure-go"
	"github.com/stretchr/testify/assert"
)

func TestExample(t *testing.T) {
	allure.Test(t,
		allure.Description("Example test"),
		allure.Action(func() {
			allure.Step(
				allure.Description("First step"),
				allure.Action(func() {
					if !assert.Equal(t, "one", "two") {
						allure.FailNow(errors.New("test returns two instead of one "))
					}
				}))
		}))
}
```
In this case, you would need to use FailNow() to balance the usage of `assert` instead of `require`. This verbose, makes the test less readable and adds lines of code to maintain.

- Implement a new Test Wrapper that overrides the testify TestingT wrapper:
```
package suites

import (
	"testing"

	"github.com/dailymotion/allure-go"
	"github.com/pkg/errors"
	"github.com/stretchr/testify/require"
)

type WrapperT struct {
	*testing.T
}

func WrapT(t *testing.T) require.TestingT {
	return WrapperT{t}
}

func (t WrapperT) Errorf(format string, args ...interface{}) {
	t.T.Errorf(format, args...)
	allure.Fail(errors.Errorf(format, args...))
}

func TestExample(t *testing.T) {
	allure.Test(t,
		allure.Description("Example test"),
		allure.Action(func() {
			require := require.New(wrapT(t))
			allure.Step(
				allure.Description("First step"),
				allure.Action(func() {
					require.Equal("one", "two") // always failed
				}))
		}))
}
```
Note that you wouldn't need to provide `t` in the requirements methods with this solution (useful in case of multiple assertions).
The wrapper type and functions could be imported from an another file (`testwrapper.go`for example), so any test in your project could easily use it by simply calling `require := require.New(testwrapper.WrapT(t))`

@ubermensch01 if you get some time before I can do it, we could create some documentation about this in the README.
